### ISSUE TITLE
Some screenshots is always good

### ISSUE THREAD

**Issue by shtefcs** [Micemade/micemade-elements#1]
Hey, i am was searching to extend Elementor and found your repo. In advance thank you for sharing it.

But, you should add some screenshots of your elements, so people know is it worth downloading and installing it.

One picture = 1000 words. Always remember that.

Peace,

**Comment by Micemade** [comment]
Yep ... sorry for delayed reply, first ... ;)
This code is still not ready for better advertising, but it will be soon ... And there will be more then screenshots :)
